class PhoneRecord:
    def __init__(self, number: str, raw: list[str] | None, kind: str, validated: bool | None, sources: list[str] | None, country: str | None, primary: bool | None) -> None: ...
    @property
    def number(self) -> str: ...
    @property
    def raw(self) -> list[str] | None: ...
    @property
    def kind(self) -> str: ...
    @property
    def validated(self) -> bool | None: ...
    @property
    def sources(self) -> list[str] | None: ...
    @property
    def country(self) -> str | None: ...
    @property
    def primary(self) -> bool | None: ...

class ParsedLink:
    def __init__(self, original: str, scheme: str, host: str | None, path: str, phone: str | None) -> None: ...

URL_PREFIXES: list[str]

def metadata_versions() -> dict[str, str]: ...
def preprocess_texts(texts: list[str]) -> list[str]: ...
def extract_text_phones(text: str, include_unknown: bool, max_year: int) -> list[PhoneRecord]: ...
def extract_json_ld_phones(phones: list[str], faxes: list[str]) -> list[PhoneRecord]: ...
def prepare_links(links: list[str], lowercase: bool) -> list[tuple[str, str]]: ...
def extract_links_phones(links: list[ParsedLink]) -> list[PhoneRecord]: ...
def validate_phones(phones: list[PhoneRecord], countries: list[str], national_format: bool) -> list[PhoneRecord]: ...
def extract_phones(text: str, phones: list[str], faxes: list[str], links: list[ParsedLink], include_unknown: bool, max_year: int) -> list[PhoneRecord]: ...
def format_numbers(numbers: list[str], national_format: bool) -> list[str | None]: ...
