[package]
name = "lzstring_optimized"
version = "0.9.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lzstring_optimized"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.29.3"
lz-str = { git = "https://github.com/spl0i7/lz-str-rs" }

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
