from collections.abc import Set

class UnsupportedDomain(ValueError): ...

def decode_idna(domain: str) -> str | None: ...

class PublicSuffixList:
    def __init__(self, suffixes: Set[str]) -> None: ...
    def is_valid_main_domain(self, domain: str) -> bool: ...
