class UnsupportedDomain(ValueError): ...

class ExtractResult:
    @property
    def subdomain(self) -> str: ...
    @property
    def domain(self) -> str: ...
    @property
    def suffix(self) -> str: ...
    @property
    def is_private(self) -> bool: ...
    @property
    def registry_suffix(self) -> str: ...
    @property
    def registered_domain(self) -> str: ...
    @property
    def top_domain_under_public_suffix(self) -> str: ...
    @property
    def fqdn(self) -> str: ...

def extract(url: str, include_psl_private_domains: bool = False) -> ExtractResult: ...
def custom_extract(url: str) -> ExtractResult: ...
def private_suffixes() -> set[str]: ...
def is_domain(value: object) -> bool: ...
def is_valid_main_domain(domain: object) -> bool: ...
def decode_idna(domain: str) -> str | None: ...
def idna_encode(domain: str) -> str | None: ...
